version: "3.3"
services:
    rstudio_docker_cuda_111:
        build:
            context: .
            dockerfile: Dockerfile
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities:
                            - gpu
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        ports:
            - 8787:8787
        volumes:
            - ../../../../rstudio_home:/home/rstudio
        restart: always
